<script>
  try {
    throw new Error("出错了");
    console.log("success");
  } catch (err) {
    console.log("error");
  } finally {
    console.log("finally");
  }
</script>
